### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by 3kh0** [MellonBunnu/MellonBunnu.github.io#6]
Hi there,

Can we please find a way to talk? I am looking forward to it!

Echo :)

**Comment by CloudyWhale** [comment]
What is it? I know the person who owns this repo in real life i can tell them if you want.

**Comment by 3kh0** [comment]
> What is it? I know the person who owns this repo in real life I can tell them if you want.

I just do not want people copying my projects without my permission or linking back to my original site. Thanks for the reply! :)

**Comment by MellonBunnu** [comment]
Hello I can take your games off my site if you want

**Comment by 3kh0** [comment]
> Hello I can take your games off my site if you want

No, you just need to state clearly that the games were from my site

**Comment by MellonBunnu** [comment]
Ok thanks I will link you site and github sorry for late response

**Comment by CloudyWhale** [comment]
I am adding a credit to the page

**Comment by CloudyWhale** [comment]
Added a fix to my pr could you merge it?

**Comment by MellonBunnu** [comment]
Ok I have to do it on a computer

> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

**Comment by MellonBunnu** [comment]
Hey,
do you mind if I use some of your progects like RUN 3 on my site?
My only gole is to not to copy stuff its to 1. make a website and 2. play game :)

**Comment by 3kh0** [comment]
> Hey, do you mind if I use some of your progects like RUN 3 on my site? My only gole is to not to copy stuff its to 1. make a website and 2. play game :)

is my site blocked for you?

**Comment by MellonBunnu** [comment]
no

**Comment by MellonBunnu** [comment]
but the prokys and holy unblooker are i spelled it wrong on perpus

**Comment by MellonBunnu** [comment]
so could you repost it under a diffrent name?
So it is useable
Also if you have any VPNs That I could use that would be grate the chrome webstore is blocked :(

**Comment by 3kh0** [comment]
> so could you repost it under a different name? So it is useable Also if you have any VPNs That I could use that would grate the chrome web store is blocked :(

what do you mean

**Comment by MellonBunnu** [comment]
The holy unblocker is blocked.

**Comment by MellonBunnu** [comment]
also Can you make a vpn with the book marker thing?

**Comment by 3kh0** [comment]
> lets chat on zenkit https://chat.zenkit.com/w/BDvgt8Qh7d

Oh no! 


![page_full_02-Dec-2021_10-54-29](https://user-images.githubusercontent.com/58097612/144456463-62af29f9-1c60-491c-9b11-43e34d76050e.png)

It does not work :(

**Comment by MellonBunnu** [comment]
gasp :(

**Comment by MellonBunnu** [comment]
whats ur email so i can invite

**Comment by 3kh0** [comment]
> whats ur email so i can invite

no email. I like to keep it private

**Comment by MellonBunnu** [comment]
ok

**Comment by 3kh0** [comment]
> ok

i have discord tho :)

**Comment by MellonBunnu** [comment]
I dont use discord

**Comment by MellonBunnu** [comment]
sry

**Comment by MellonBunnu** [comment]
do you have a way to rpost the holy unblocker and btw your website is now blocked :(

**Comment by MellonBunnu** [comment]
oh ok

**Comment by MellonBunnu** [comment]
thanks I look forward to not doing what i am soppost to

**Comment by MellonBunnu** [comment]
Also do you know a bookmark vpn i can use?

**Comment by 3kh0** [comment]
> Also do you know a bookmark vpn i can use?

uhhh no

**Comment by CloudyWhale** [comment]
The problem that your website is blocked is  with the school district I go to they put your website on their block list

**Comment by 3kh0** [comment]
> The problem that your website is blocked is with the school district I go to they put your website on their block list

Oh wow, that's crazy! I am making alternate links to the site. Do you know if the whole domain ( .github.io ) or just my site ( 3kh0.github.io ) is blocked?

**Comment by CloudyWhale** [comment]
it is specifically your website

**Comment by 3kh0** [comment]
> it is specifically your website

ok, thank you for the feedback! 😄

**Comment by MellonBunnu** [comment]
Ah

**Comment by MellonBunnu** [comment]
Bh

**Comment by MellonBunnu** [comment]
Ch

**Comment by MellonBunnu** [comment]
Dh

**Comment by MellonBunnu** [comment]
Eh

**Comment by MellonBunnu** [comment]
Fh

**Comment by MellonBunnu** [comment]
Gh

**Comment by MellonBunnu** [comment]
Hh

**Comment by MellonBunnu** [comment]
Ih

**Comment by MellonBunnu** [comment]
Jh

**Comment by MellonBunnu** [comment]
Kh

**Comment by MellonBunnu** [comment]
Lh

**Comment by MellonBunnu** [comment]
Nh

**Comment by MellonBunnu** [comment]
Mh

**Comment by MellonBunnu** [comment]
Oh

**Comment by MellonBunnu** [comment]
Ph

**Comment by MellonBunnu** [comment]
Qh

**Comment by MellonBunnu** [comment]
Rh

**Comment by MellonBunnu** [comment]
Sh

**Comment by MellonBunnu** [comment]
Z

**Comment by MellonBunnu** [comment]
hellog

**Comment by 3kh0** [comment]
hi?

**Comment by CloudyWhale** [comment]
I'm gonna close this now

**Comment by CloudyWhale** [comment]
issue was fixed
